services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Keep CSV data in sync with the host so it persists across rebuilds
      - ./data:/app/data
    restart: unless-stopped
