services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROD: ${PROD:-true}
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    # Bind-mount the project into the container (useful in dev)
    # volumes:
    #   - ./:/app:cached
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 60
      start_period: 2s
    restart: unless-stopped
    # Run with auto-reload only when PROD is false
    command: >
      bash -lc 'if [ "${PROD:-true}" = "false" ]; then
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload;
      else
        uvicorn app.main:app --host 0.0.0.0 --port 8000;
      fi'

  
