services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROD: ${PROD:-true}
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 60
      start_period: 2s
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@db:5432/mytodo}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mytodo
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mytodo"]
      interval: 2s
      timeout: 3s
      retries: 60
      start_period: 5s

volumes:
  pgdata:
