services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROD: ${PROD:-true}
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      MAX_SESSIONS: 50
      EVICT_ON_GET: true
    depends_on:
      - redis
    # Dev bind mount (uncommented); use ':cached' only on Docker Desktop/macOS
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 2s
      timeout: 1s
      retries: 60
      start_period: 2s
    restart: unless-stopped
    # Run with auto-reload only when PROD is false
    command: >
      bash -lc 'if [ "${PROD:-true}" = "false" ]; then
        uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload;
      else
        uvicorn backend.app:app --host 0.0.0.0 --port 8000;
      fi'
