[tool.poetry]
name = "my-todo"
version = "0.1.0"
description = "Tiny TODO API (FastAPI + Postgres)"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
uvicorn = { version = "^0.35.0", extras = ["standard"] }
pydantic = "^2.11.6"
passlib = { version = "^1.7.4", extras = ["bcrypt"] }
PyJWT = "^2.10.1"
python-dotenv = "^1.0.1"
SQLAlchemy = "^2.0.36"
psycopg = {version = "^3.2.9", extras = ["binary"]}

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-xdist = "^3.6.1"
requests = "^2.32.3"
pytest-timeout = "^2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
